// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a6b0c2a-9b4f-4a09-8b8e-8a2b0c6d7e0f"),
                            Name = "USA"
                        },
                        new
                        {
                            Id = new Guid("8b5f3a0c-4d7e-4b9e-8b4f-0a8c1e6d7b2a"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("c4a0b6e8-2d7c-4a0b-8d6f-1a9c2e7d8b3a"),
                            Name = "United Kingdom"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("ReceiveNewsletter")
                        .HasColumnType("bit");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("f1a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            Address = "123 Main St, New York",
                            CountryId = new Guid("1a6b0c2a-9b4f-4a09-8b8e-8a2b0c6d7e0f"),
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@example.com",
                            Gender = "Male",
                            Name = "John Smith",
                            ReceiveNewsletter = true
                        },
                        new
                        {
                            PersonId = new Guid("a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6"),
                            Address = "456 Nile Corniche, Cairo",
                            CountryId = new Guid("8b5f3a0c-4d7e-4b9e-8b4f-0a8c1e6d7b2a"),
                            DateOfBirth = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.alsayed@example.com",
                            Gender = "Female",
                            Name = "Fatima Al-Sayed",
                            ReceiveNewsletter = false
                        },
                        new
                        {
                            PersonId = new Guid("e8b1b2a9-1d9c-4c6b-9f1e-3a7d5c9f2b8a"),
                            Address = "10 Downing St, London",
                            CountryId = new Guid("c4a0b6e8-2d7c-4a0b-8d6f-1a9c2e7d8b3a"),
                            DateOfBirth = new DateTime(1970, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.bond@mi6.gov.uk",
                            Gender = "Male",
                            Name = "James Bond",
                            ReceiveNewsletter = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
